name = "ai-ink"
compatibility_date = "2025-09-28"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

# Environment variables for both production and preview
[vars]
OPENAI_API_KEY = "your-openai-api-key-here"