name = "ai-ink"
compatibility_date = "2025-09-28"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

# Environment variables for both production and preview
[vars]
VITE_FIREBASE_API_KEY = "AlzaSyAy-IH56f2DtXPp5wXIWGaY_vIiaoVVbyuM"
VITE_FIREBASE_AUTH_DOMAIN = "aiink-231e7.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "aiink-231e7"
VITE_FIREBASE_APP_ID = "1:198276519701:web:c5e8f7a8b9d1e2f3g4h5i6j7"
OPENAI_API_KEY = "your-openai-api-key-here"