name = "ai-ink"
compatibility_date = "2025-09-28"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm ci && npm run build"

# Production environment variables will be configured in Cloudflare Dashboard
# [vars]
# OPENAI_API_KEY = "your-openai-api-key-here"